Tui divider component is created
tarkalabs/tarka-ui-kit-android pull request #171
Opened 2024-01-23 06:13 UTC by sheshadhreens

2024-01-23 07:31 UTC, Younes-Charfaoui approved these changes

2024-01-23 07:31 UTC, Younes-Charfaoui commented on tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIDivider.kt
> +            // .height(40.dp)
What should we do to either remove this or find a value for it!

2024-01-23 07:35 UTC, sheshadhreens commented on tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIDivider.kt
> +            // .height(40.dp)
its cleaned

2024-01-24 11:01 UTC, askNilesh approved these changes

2024-01-25 13:13 UTC, rajajawahar requested changes

2024-01-25 13:13 UTC, rajajawahar commented on tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIMultiLevelSelectorHeader.kt
> +    leadingIcon: TarkaIcon,
We should not be passing this trailingIcon and leadingIcon

2024-01-27 10:47 UTC, rajajawahar approved these changes

2024-01-29 03:46 UTC, merged