feature: Title with NotAvailable Style introduced in TextRow
tarkalabs/tarka-ui-kit-android pull request #204
Opened 2024-02-28 09:16 UTC by rajajawahar

###$ [TUIPopUpMenu style introduced](https://github.com/tarkalabs/tarka-ui-kit-android/commit/0679842ca1bcffb92546988d7432027c65c0ff66)

2024-02-28 09:40 UTC, androidmahi requested changes

2024-02-28 09:40 UTC, androidmahi commented on tarka-ui/src/main/res/values/strings.xml
> +  <string name="not_availble">Not Available</string>
What about other language translations. I think it's better to pass translated string or res via param in this component.

2024-02-28 09:40 UTC, androidmahi commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUITextRow.kt
> +interface TUIPopUpMenu {
Why we removed Item prefix here ?

2024-02-28 10:14 UTC, rajajawahar commented on tarka-ui/src/main/res/values/strings.xml
> +  <string name="not_availble">Not Available</string>
@androidmahi Mahi, we are passing dynamic value, not a hardcoded string. check the TextRow style. it has a parameter called text. Consumer can choose a string whatever he wants.

2024-02-28 10:15 UTC, rajajawahar commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUITextRow.kt
> +interface TUIPopUpMenu {
@androidmahi Since consumer needs to implement this interface. This can be actually either way.

2024-02-28 13:46 UTC, Mohanraj293 approved these changes

2024-02-28 14:04 UTC, androidmahi approved these changes

2024-02-28 14:08 UTC, MadhuMathiR approved these changes

2024-02-29 05:20 UTC, askNilesh approved these changes

2024-02-29 10:41 UTC, merged