TUIIconButton updated with custom style.
tarkalabs/tarka-ui-kit-android pull request #217
Opened 2024-03-29 05:16 UTC by Mohanraj293

2024-03-29 10:05 UTC, rajajawahar requested changes

2024-03-29 10:05 UTC, rajajawahar commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/base/TUIIconButton.kt
> +  data class Custom(val color: Color) : IconButtonStyle()
I think we should both the colors right `container color` and `content color`

2024-03-30 05:31 UTC, Younes-Charfaoui approved these changes

2024-04-01 05:21 UTC, askNilesh approved these changes

2024-04-01 09:58 UTC, merged