Implemented TUIAppBottomBar
tarkalabs/tarka-ui-kit-android pull request #253
Opened 2024-06-07 06:51 UTC by priyacs651

<img width="370" alt="Screenshot 2024-06-07 at 11 31 40 AM" src="https://github.com/tarkalabs/tarka-ui-kit-android/assets/89240241/7172263b-7484-4ed1-ada8-23750cf8c1ca">

2024-06-07 09:48 UTC, deekshitheam360 approved these changes

2024-06-07 11:25 UTC, Meg979 commented on tarka-ui/build.gradle.kts
> +        version = "1.1.31"
I have already increased the version in one of my previous PR's & it isn't released yet.  
You can revert this.

2024-06-07 11:25 UTC, Meg979 commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +    temIconSix: TarkaIcon? = null,
There is a typo here.

2024-06-07 11:25 UTC, Meg979 commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +                        tags = tags.itemIconTwoTags,
Please check the tag set for all the icons.

2024-06-07 11:25 UTC, Meg979 commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +                        icon = itemIconTwo, tags = tags.itemIconThreeTags,
Please set the correct tag for the icon

2024-06-07 15:07 UTC, Meg979 approved these changes

2024-06-10 15:33 UTC, askNilesh requested changes

2024-06-10 15:33 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +    onClickEvent: (BottomBarClickEvent) -> Unit = {},
Do we really required this `BottomBarClickEvent` can't directly pass index like this

```
onClickEvent: (index: Int) -> Unit ,
```

2024-06-10 15:33 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +    icons: List<TarkaIcon?> = emptyList(),
We should not pass nullable tarkaicon here
```suggestion
    icons: List<TarkaIcon>,
```

2024-06-10 15:33 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +                            tags = tags[index],
we shold add some king of validation here because `tags` non mentory field if you list is empty than it will crash here

2024-06-10 15:33 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +                icons.forEachIndexed { index, icon ->
Do we have some kind of validation here like how many maximum item allowed in `TUIAppBottomBar`

2024-06-13 16:54 UTC, deekshitheam360 commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +                    TUIIconButtonTags(parentTag = "TUITopBar_itemIconFour"),
@priyacs651 check tag

2024-06-13 16:57 UTC, deekshitheam360 approved these changes

2024-06-14 14:30 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +    require(defaultSelectedItem < 6 && icons.size <= 6 && tags.size <= 6) { "icon and tags should not exceed more 6" }
`tags` should optinal

2024-06-14 14:30 UTC, askNilesh commented on tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppBottomBar.kt
> +    var selectedIconIndex by remember { mutableIntStateOf(defaultSelectedItem) } // Initially, the second icon is selected
Please remove this comment

2024-10-23 20:32 UTC, closed without merging